# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.7

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - test
  - pages
  - deploy

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - docker info
  - pip install -r requirements.txt

test:
  script:
    - pip install flake8 # you can also use tox
    - pytest
    - flake8 --max-line-length=80 ./*.py
    - flake8 --max-line-length=80 ./uuid_module/*.py
    # - tox -e py36,flake8

pages:
  script:
    - pip install pdoc smartsheet-python-sdk
    - pdoc -o docs/ -d google uuid_module
    - mkdir ./public
    - mv ./docs/* ./public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
    # - python __main__.py
  environment:
    name: Staging

deploy_prod:
  stage: deploy
  script:
    -echo "Deploy to production server"
    # - python __main__.py
  environment:
    name: Production
  when: manual
  only:
    - main