FROM python:3
RUN pip3 install smartsheet-python-sdk
RUN pip3 install apscheduler
RUN pip3 install python-dotenv
RUN pip3 install dumb-init
ENV SMARTSHEET_ACCESS_TOKEN="[API ACCESS TOKEN]"
ENV PYTHONUNBUFFERED=1
RUN mkdir uuid
CMD ["stdbuf", "-oL", "python", "-u", "/uuid/__main__.py"]